# Generated by Django 5.1 on 2024-10-08 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_go', '0007_cinema_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='views',
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='Адрес Ip')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cinema_go.cinema', verbose_name='Кинофильм')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ip Пользователя',
                'verbose_name_plural': 'Ip пользователей',
            },
        ),
    ]
